version: '3.3'

services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    networks:
      - new
    environment:
      MYSQL_DATABASE: 'game_chat_db'
      MYSQL_USER: 'game_chat'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "database"]
      timeout: 20s
      retries: 10
  
  migrate:
    container_name: migrate
    image: migrate/migrate
    restart: on-failure
    networks:
      - new
    volumes:
      - ./migrations:/migrations
    command: -path=/migrations -database "mysql://game_chat:password@tcp(db:3306)/game_chat_db" up
    depends_on:
      - db

  app:
    container_name: app
    build: .
    restart: on-failure
    networks:
      - new
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate

volumes:
  my-db:

networks:
  new:
