version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    networks:
      new:
        aliases:
          - database
    environment:
      MYSQL_DATABASE: 'game_chat_db'
      MYSQL_USER: 'game_chat'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  
  migarte:
    image: migrate/migrate
    networks:
      - new
    command: migrate -path migrations -database "mysql://game_chat:password@tcp(database:3306)/game_chat_db" up
    links:
      - db
    depends_on:
      - db

  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - "8080:8080"
    depends_on:
      - migrate
      - db

volumes:
  my-db:

networks:
  new:
